include:
  - proxy.yaml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: shvirtd-web
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=example
      - DB_USER=webuser
      - DB_PASSWORD=WebUserPass456
    command: >
      sh -c "sleep 60 && uvicorn main:app --host 0.0.0.0 --port 5000"
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=StrongRootPass123
      - MYSQL_DATABASE=example
      - MYSQL_USER=webuser
      - MYSQL_PASSWORD=WebUserPass456
    networks:
      backend:
        ipv4_address: 172.20.0.10

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

